# Generated by Django 6.1 on 2026-09-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
