# Generated by Django 6.1 on 2026-09-16 07:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_journal', '0004_workout_hot_filter_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5, message='Duration must be between 5 and 900 seconds.'), django.core.validators.MaxValueValidator(900, message='Duration must be between 5 and 900 seconds.')]),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='reps',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Reps must be at least 1.')]),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='Weight cannot be negative.')]),
        ),
    ]
